<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ include file="/common/taglibs.jsp" %>
<li id="m"><a <c:choose><c:when test="${cssclass=='userMain'}">class='mbacka'</c:when><c:otherwise>class='mback'</c:otherwise></c:choose> class="mback" href="${ctx}/ismp/domain/local/userConfig.do?method=getBlurUser&all=true"><span class="menus01">用户浏览</span></a></li>
      <li><a  <c:choose><c:when test="${cssclass=='userToManager'}">class='mbacka'</c:when><c:otherwise>class='mback'</c:otherwise></c:choose> class="mback" href="${ctx}/ismp/domain/local/userConfig.do?method=getRoleAll"><span class="menus02">用户条件查询</span></a></li>
      <li><a <c:choose><c:when test="${cssclass=='userBlackandWhiteSearch'}">class='mbacka'</c:when><c:otherwise>class='mback'</c:otherwise></c:choose> class="mback" href="${ctx}/ismp/domain/local/userConfig.do?method=forward&blackandwhiteFwd=1"><span class="menus03">黑白名单查询</span></a></li>
      <li><a <c:choose><c:when test="${cssclass=='userRegister'}">class='mbacka'</c:when><c:otherwise>class='mback'</c:otherwise></c:choose> class="mback" href="${ctx}/ismp/domain/local/userConfig.do?method=forward&add=1"><span class="menus04">新增用户</span></a></li>
      <li><a <c:choose><c:when test="${cssclass=='addBlackAndWhite'}">class='mbacka'</c:when><c:otherwise>class='mback'</c:otherwise></c:choose> class="mback" href="${ctx}/ismp/domain/local/userConfig.do?method=forward&addBlackAndWhite=1"><span class="menus05">新增黑白名单</span></a></li>
      <li><a <c:choose><c:when test="${cssclass=='blackandwhitestatus'}">class='mbacka'</c:when><c:otherwise>class='mback'</c:otherwise></c:choose> class="mback" href="${ctx}/ismp/domain/local/userConfig.do?method=getBlackandWhiteStatus"><span class="menus06">黑白名单状态管理</span></a></li>
     <!-- <li><a <c:choose><c:when test="${cssclass=='userToManager'}">class='mbacka'</c:when><c:otherwise>class='mback'</c:otherwise></c:choose> class="mbacka" href="${ctx}/ismp/domain/local/userConfig.do?method=getUserToManagerByList"><span class="menus07">部门管理</span></a></li> -->
      <li><a <c:choose><c:when test="${cssclass==null}">class='mbacka'</c:when><c:otherwise>class='mback'</c:otherwise></c:choose> class="mback" href="${ctx}/ismp/domain/local/userResetPassword.do"><span class="menus08">密码重置</span></a></li> 