package org.infosec.ismp.agent.comm.winsensor.model.strategy;

import java.io.Serializable;
import java.util.Date;

/**
 * @author Rocky
 * @version create time：Dec 6, 2010 1:49:17 PM
 * 
 */
public class CommBaseStrategy implements Serializable {

	private static final long serialVersionUID = -8992101297075065155L;

	private Date createTime;		//Strategy create time;
	
	private String ip;		//Sensor client ip;
	
	private String sensorId;		//Sensor client id;
	
	private long remoteId;		//Strategy identifies generated by the web client.

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getIp() {
		return ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getSensorId() {
		return sensorId;
	}

	public void setSensorId(String sensorId) {
		this.sensorId = sensorId;
	}

	public long getRemoteId() {
		return remoteId;
	}

	public void setRemoteId(long remoteId) {
		this.remoteId = remoteId;
	}
}
