--拓扑发现
insert into `tm_find_node_types` (`id`, `add_date`, `description`, `english_tag`, `fullclass_name`, `ico_path`, `image_path`, `name`, `remarks`, `update_date`) values('1',NULL,NULL,'router','edu.sjtu.infosec.ismp.manager.applet.topomanage.model.TopoRouterModel','/images/topo/topomanage/bw/2.gif','/images/topo/topomanage/bw/12.gif','路由器',NULL,NULL);
insert into `tm_find_node_types` (`id`, `add_date`, `description`, `english_tag`, `fullclass_name`, `ico_path`, `image_path`, `name`, `remarks`, `update_date`) values('2',NULL,NULL,'switch','edu.sjtu.infosec.ismp.manager.applet.topomanage.model.TopoSwitchModel','/images/topo/topomanage/bw/4.gif','/images/topo/topomanage/bw/14.gif','三层交换机',NULL,NULL);
insert into `tm_find_node_types` (`id`, `add_date`, `description`, `english_tag`, `fullclass_name`, `ico_path`, `image_path`, `name`, `remarks`, `update_date`) values('3',NULL,NULL,'pc','edu.sjtu.infosec.ismp.manager.applet.topomanage.model.TopoSnmpModel','/images/topo/topomanage/bw/3.gif','/images/topo/topomanage/bw/13.gif','PC',NULL,NULL);
insert into `tm_find_node_types` (`id`, `add_date`, `description`, `english_tag`, `fullclass_name`, `ico_path`, `image_path`, `name`, `remarks`, `update_date`) values('4',NULL,NULL,'firewall','edu.sjtu.infosec.ismp.manager.applet.topomanage.model.TopoFirewallModel','/images/topo/topomanage/bw/6.gif','/images/topo/topomanage/bw/16.gif','防火墙',NULL,NULL);
insert into `tm_find_node_types` (`id`, `add_date`, `description`, `english_tag`, `fullclass_name`, `ico_path`, `image_path`, `name`, `remarks`, `update_date`) values('5',NULL,NULL,NULL,'edu.sjtu.infosec.ismp.manager.applet.topomanage.model.TopoAntiViruswallModel','/images/topo/topomanage/bw/32.gif','/images/topo/topomanage/bw/43.gif','防毒墙',NULL,NULL);
insert into `tm_find_node_types` (`id`, `add_date`, `description`, `english_tag`, `fullclass_name`, `ico_path`, `image_path`, `name`, `remarks`, `update_date`) values('6',NULL,NULL,'switch','edu.sjtu.infosec.ismp.manager.applet.topomanage.model.TopoSwitchModel','/images/topo/topomanage/bw/4.gif','/images/topo/topomanage/bw/14.gif','二层交换机',NULL,NULL);
insert into `tm_find_node_types` (`id`, `add_date`, `description`, `english_tag`, `fullclass_name`, `ico_path`, `image_path`, `name`, `remarks`, `update_date`) values('7',NULL,NULL,'server','edu.sjtu.infosec.ismp.manager.applet.topomanage.model.TopoServerModel','/images/topo/topomanage/bw/1.gif','/images/topo/topomanage/bw/11.gif','服务器',NULL,NULL);
insert into `tm_find_node_types` (`id`, `add_date`, `description`, `english_tag`, `fullclass_name`, `ico_path`, `image_path`, `name`, `remarks`, `update_date`) values('8',NULL,NULL,'sealed','edu.sjtu.infosec.ismp.manager.applet.topomanage.model.TopoSealedModel','/images/topo/topomanage/bw/3.gif','/images/topo/topomanage/bw/13.gif','未知设备',NULL,NULL);
insert into `tm_find_node_types` (`id`, `add_date`, `description`, `english_tag`, `fullclass_name`, `ico_path`, `image_path`, `name`, `remarks`, `update_date`) values('9',NULL,NULL,'ids','edu.sjtu.infosec.ismp.manager.applet.topomanage.model.TopoIdsModel','/images/topo/topomanage/bw/5.gif','/images/topo/topomanage/bw/15.gif','IDS',NULL,NULL);


insert into `tm_find_device_types_ruler` (`id`, `add_date`, `description`, `key_chars`, `level`, `name`, `oid`, `remarks`, `update_date`, `type`) values('1',NULL,NULL,'Ruijie',NULL,'Ruijie-S6506','.1.3.6.1.2.1.1.1',NULL,NULL,'2');
insert into `tm_find_device_types_ruler` (`id`, `add_date`, `description`, `key_chars`, `level`, `name`, `oid`, `remarks`, `update_date`, `type`) values('2',NULL,NULL,'S6506',NULL,'Ruijie-S6506','.1.3.6.1.2.1.1.1',NULL,NULL,'2');
insert into `tm_find_device_types_ruler` (`id`, `add_date`, `description`, `key_chars`, `level`, `name`, `oid`, `remarks`, `update_date`, `type`) values('3',NULL,NULL,'.1.3.6.1.4.1.4881.1.1.10.1.22',NULL,'Ruijie-S6506','.1.3.6.1.2.1.1.2',NULL,NULL,'2');
insert into `tm_find_device_types_ruler` (`id`, `add_date`, `description`, `key_chars`, `level`, `name`, `oid`, `remarks`, `update_date`, `type`) values('4',NULL,NULL,'Cisco',NULL,'Cisco-C3560','.1.3.6.1.2.1.1.1',NULL,NULL,'2');
insert into `tm_find_device_types_ruler` (`id`, `add_date`, `description`, `key_chars`, `level`, `name`, `oid`, `remarks`, `update_date`, `type`) values('5',NULL,NULL,'C3560',NULL,'Cisco-C3560','.1.3.6.1.2.1.1.1',NULL,NULL,'2');
insert into `tm_find_device_types_ruler` (`id`, `add_date`, `description`, `key_chars`, `level`, `name`, `oid`, `remarks`, `update_date`, `type`) values('6',NULL,NULL,'.1.3.6.1.4.1.9.1.633',NULL,'Cisco-C3560','.1.3.6.1.2.1.1.2',NULL,NULL,'2');
insert into `tm_find_device_types_ruler` (`id`, `add_date`, `description`, `key_chars`, `level`, `name`, `oid`, `remarks`, `update_date`, `type`) values('7',NULL,NULL,'H3C',NULL,'H3C S5100-48P-EI','.1.3.6.1.2.1.1.1',NULL,NULL,'6');
insert into `tm_find_device_types_ruler` (`id`, `add_date`, `description`, `key_chars`, `level`, `name`, `oid`, `remarks`, `update_date`, `type`) values('8',NULL,NULL,'S5100-48P-EI',NULL,'H3C S5100-48P-EI','.1.3.6.1.2.1.1.1',NULL,NULL,'6');
insert into `tm_find_device_types_ruler` (`id`, `add_date`, `description`, `key_chars`, `level`, `name`, `oid`, `remarks`, `update_date`, `type`) values('9',NULL,NULL,'1.3.6.1.4.1.25506.1.31',NULL,'H3C S5100-48P-EI','.1.3.6.1.2.1.1.2',NULL,NULL,'6');
insert into `tm_find_device_types_ruler` (`id`, `add_date`, `description`, `key_chars`, `level`, `name`, `oid`, `remarks`, `update_date`, `type`) values('10',NULL,NULL,'H3C',NULL,'H3C S7502E','.1.3.6.1.2.1.1.1',NULL,NULL,'2');
insert into `tm_find_device_types_ruler` (`id`, `add_date`, `description`, `key_chars`, `level`, `name`, `oid`, `remarks`, `update_date`, `type`) values('11',NULL,NULL,'S7502E',NULL,'H3C S7502E','.1.3.6.1.2.1.1.1',NULL,NULL,'2');
insert into `tm_find_device_types_ruler` (`id`, `add_date`, `description`, `key_chars`, `level`, `name`, `oid`, `remarks`, `update_date`, `type`) values('12',NULL,NULL,'1.3.6.1.4.1.25506.1.207',NULL,'H3C S7502E','.1.3.6.1.2.1.1.2',NULL,NULL,'2');
insert into `tm_find_device_types_ruler` (`id`, `add_date`, `description`, `key_chars`, `level`, `name`, `oid`, `remarks`, `update_date`, `type`) values('13',NULL,NULL,'H3C',NULL,'H3C S7506E','.1.3.6.1.2.1.1.1',NULL,NULL,'2');
insert into `tm_find_device_types_ruler` (`id`, `add_date`, `description`, `key_chars`, `level`, `name`, `oid`, `remarks`, `update_date`, `type`) values('14',NULL,NULL,'S7506E',NULL,'H3C S7506E','.1.3.6.1.2.1.1.1',NULL,NULL,'2');
insert into `tm_find_device_types_ruler` (`id`, `add_date`, `description`, `key_chars`, `level`, `name`, `oid`, `remarks`, `update_date`, `type`) values('15',NULL,NULL,'1.3.6.1.4.1.25506.1.209',NULL,'H3C S7506E','.1.3.6.1.2.1.1.2',NULL,NULL,'2');
insert into `tm_find_device_types_ruler` (`id`, `add_date`, `description`, `key_chars`, `level`, `name`, `oid`, `remarks`, `update_date`, `type`) values('16',NULL,NULL,'HP',NULL,'HP 1/10Gb VC-Enet Module Virtual Connect 1.34','.1.3.6.1.2.1.1.1',NULL,NULL,'2');
insert into `tm_find_device_types_ruler` (`id`, `add_date`, `description`, `key_chars`, `level`, `name`, `oid`, `remarks`, `update_date`, `type`) values('17',NULL,NULL,'1/10Gb VC-Enet Module Virtual Connect 1.34',NULL,'HP 1/10Gb VC-Enet Module Virtual Connect 1.34','.1.3.6.1.2.1.1.1',NULL,NULL,'2');
insert into `tm_find_device_types_ruler` (`id`, `add_date`, `description`, `key_chars`, `level`, `name`, `oid`, `remarks`, `update_date`, `type`) values('18',NULL,NULL,'1.3.6.1.4.1.11.5.7.5.1',NULL,'HP 1/10Gb VC-Enet Module Virtual Connect 1.34','.1.3.6.1.2.1.1.2',NULL,NULL,'2');
insert into `tm_find_device_types_ruler` (`id`, `add_date`, `description`, `key_chars`, `level`, `name`, `oid`, `remarks`, `update_date`, `type`) values('19',NULL,NULL,'Topsec',NULL,'天融信 NGF W4000-UF','.1.3.6.1.2.1.1.1',NULL,NULL,'4');
insert into `tm_find_device_types_ruler` (`id`, `add_date`, `description`, `key_chars`, `level`, `name`, `oid`, `remarks`, `update_date`, `type`) values('20',NULL,NULL,'Firewall',NULL,'天融信 NGF W4000-UF','.1.3.6.1.2.1.1.1',NULL,NULL,'4');
insert into `tm_find_device_types_ruler` (`id`, `add_date`, `description`, `key_chars`, `level`, `name`, `oid`, `remarks`, `update_date`, `type`) values('21',NULL,NULL,'1.3.6.1.4.1.14331.1.4',NULL,'天融信 NGF W4000-UF','.1.3.6.1.2.1.1.2',NULL,NULL,'4');
insert into `tm_find_device_types_ruler` (`id`, `add_date`, `description`, `key_chars`, `level`, `name`, `oid`, `remarks`, `update_date`, `type`) values('22',NULL,NULL,'NSFOCUS',NULL,'绿盟 ICEYE 1208D','.1.3.6.1.2.1.1.6',NULL,NULL,'9');
insert into `tm_find_device_types_ruler` (`id`, `add_date`, `description`, `key_chars`, `level`, `name`, `oid`, `remarks`, `update_date`, `type`) values('23',NULL,NULL,'1.3.6.1.4.1.19849',NULL,'绿盟 ICEYE 1208D','.1.3.6.1.2.1.1.2',NULL,NULL,'9');
insert into `tm_find_device_types_ruler` (`id`, `add_date`, `description`, `key_chars`, `level`, `name`, `oid`, `remarks`, `update_date`, `type`) values('24',NULL,NULL,'Hardware: x86',NULL,'PC','.1.3.6.1.2.1.1.1',NULL,NULL,'3');
insert into `tm_find_device_types_ruler` (`id`, `add_date`, `description`, `key_chars`, `level`, `name`, `oid`, `remarks`, `update_date`, `type`) values('25',NULL,NULL,'1.3.6.1.4.1.311.1.1.3.1.1',NULL,'PC','.1.3.6.1.2.1.1.2',NULL,NULL,'3');





--拓扑管理
insert  into `tm_topo_node_type`(`type_id`,`active_big_image`,`active_small_image`,`active_un_line_big_image`,`active_un_line_small_image`,`english_name`,`name`,`type_object`,`un_active_gray_big_image`,`un_active_gray_small_image`) values (1,NULL,NULL,NULL,NULL,'router',NULL,NULL,NULL,NULL),(2,NULL,NULL,NULL,NULL,'switch',NULL,NULL,NULL,NULL),(3,NULL,NULL,NULL,NULL,'pc',NULL,NULL,NULL,NULL),(4,NULL,NULL,NULL,NULL,'firewall',NULL,NULL,NULL,NULL),(5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(6,NULL,NULL,NULL,NULL,'switch',NULL,NULL,NULL,NULL),(7,NULL,NULL,NULL,NULL,'server',NULL,NULL,NULL,NULL),(8,NULL,NULL,NULL,NULL,'sealed',NULL,NULL,NULL,NULL),(9,NULL,NULL,NULL,NULL,'ids',NULL,NULL,NULL,NULL),(10,NULL,NULL,NULL,NULL,'weblogic',NULL,NULL,NULL,NULL),(11,NULL,NULL,NULL,NULL,'database',NULL,NULL,NULL,NULL);

insert  into `tm_topo_manager_device_brand`(`brand_id`,`english_name`,`name`) values (1,'cisco','思科'),(2,'h3c','华三'),(3,'leadsec','联想'),(4,'topsec','天融信'),(5,'venustech','启明星辰'),(6,'huatang','华堂'),(7,'hp','惠普'),(8,'adt','安达通'),(9,'lm','绿盟'),(10,'dell','戴尔'),(11,'hy','华依'),(12,'ht    ','华堂'),(13,'trend','趋势科技'),(14,'hammer','港湾'),(15,'baystack','北电'),(16,'digital','神州数码'),(17,'ovislink','ovislink'),(18,'huawei','华为'),(19,'dlink','D_Link');

insert  into `tm_topo_manager_device_model`(`model_id`,`en_name`,`name`,`brand_id`) values (1,NULL,'S3600',3),(2,NULL,'ABC-1100',2),(3,NULL,'W4000-UF',4),(4,NULL,'S1600',1),(5,NULL,'ABC-1100',5),(6,NULL,'ABC-11001',6),(7,NULL,'BL460C',7),(8,NULL,'DL580G5',7),(9,NULL,'DL380G5',7),(10,NULL,'SJW74C pro',8),(11,NULL,'AURORA-X',8),(12,NULL,'NIDS',9),(13,NULL,'S5100',2),(14,NULL,'HP DX2310MT',7),(15,NULL,'dl-585',10),(16,NULL,'HY-F2000+(E)',11),(17,NULL,'HT-1000',6),(18,NULL,'HT-2500',6),(19,NULL,'PIX525',1),(20,NULL,'1800S-V2',16),(21,NULL,'NDE-NS200',5),(22,NULL,'NDE-NS500',5),(23,NULL,'TRENDmicro-1200',13),(24,NULL,'4506',1),(25,NULL,'3750',1),(26,NULL,'3745',1),(27,NULL,'3550',1),(28,NULL,'Cisco3500 XL',1),(29,NULL,'6808',14),(30,NULL,'2960',1),(31,NULL,'2950',1),(32,NULL,'2924',1),(33,NULL,'1924',1),(34,NULL,'1900',1),(35,NULL,'NBaystack450-24TULL',15),(36,NULL,'Ovislink ether FSH 2400RS',17),(37,NULL,'S1526',18),(38,NULL,'switch 4400SEs',2),(39,NULL,'DES-1016D',19),(40,NULL,'5610T',14),(41,NULL,'7506E',2),(42,NULL,'7502E',2),(43,NULL,'S3100',2),(44,NULL,'S5100',2),(45,NULL,'S7500E',2),(46,NULL,'POWER V',3),(47,NULL,'S3100',2),(49,NULL,'NGFW4000-UF TG-5328',4),(50,NULL,'Bighammer 6808',14),(51,NULL,'hammer 5610T',14),(52,NULL,'NetHammerM582',16),(53,NULL,'3560G',1),(54,NULL,'TG5218',4),(55,NULL,'3560G',1),(56,NULL,'TG5218',4);
